subject_identifier = '[B|C]142\-[0-9A-Z\-]+'
child_subject_identifier = r'.*'
screening_identifier = '[A-Z0-9]{8}'
study_maternal_identifier = '066-[0-9\-]+'
group_identifier = '[FGF]142\-[0-9A-Z\-]+'
